const FETCH_TRANSACTIONS = "FETCH_TRANSACTIONS";
const FETCH_TRANSACTIONS_SUCCESS = "FETCH_TRANSACTIONS_SUCCESS";
const FETCH_TRANSACTIONS_FAILED = "FETCH_TRANSACTIONS_FAILED";
const ADD_TRANSACTION = "ADD_TRANSACTION";
const EDIT_TRANSACTION = "EDIT_TRANSACTION";
const DELETE_TRANSACTION = "DELETE_TRANSACTION";
const SET_FILTER = "SET_FILTER";


export {
    FETCH_TRANSACTIONS,
    FETCH_TRANSACTIONS_SUCCESS,
    FETCH_TRANSACTIONS_FAILED,
    ADD_TRANSACTION,
    EDIT_TRANSACTION,
    DELETE_TRANSACTION,
    SET_FILTER
};